apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentservice
spec:
  selector:
    matchLabels:
      app: commentservice
  template:
    metadata:
      labels:
        app: commentservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: commentservice
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi